FROM php:8.4-fpm

# Install PHP extensions
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

RUN install-php-extensions \
    gd \
    intl \
    zip \
    opcache \
    pdo_pgsql \
    ctype \
    iconv

WORKDIR /var/www/html

#  copy full project 
COPY . .

#  composer
COPY --from=composer:2 /usr/bin/composer /usr/local/bin/composer

ENV COMPOSER_ALLOW_SUPERUSER=1

#  env
RUN cp .env.example .env

#  install deps
RUN composer install --no-dev --optimize-autoloader

#  generate key
RUN php artisan key:generate

EXPOSE 9000