version: '3.8'

services:
  app:
    build: .
    container_name: rarecare_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: rarecare_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: rarecare
    ports:
      - "5432:5432"
